### ISSUE TITLE
このコードってどういう意味ですか?

### ISSUE THREAD

**Issue by javaboy-github** [neknaj/virtualworld#1]
https://github.com/neknaj/virtualworld/blob/4025f1989e6d84c0a8c04911bd78f1e6ad659cff/data/3d.js#L120
Dev Toolsで見たところps[*].lengthは5なんで、左辺も右辺もundefinedに評価されます。何をしようとしてるんですか?

**Comment by bem130** [comment]
教えて頂きありがとうございます

そこは、ポリゴンまでの距離によって、並び替えをする部分です
配列の不要な要素を削ったので、本来は`ps[j][4]>ps[j+1][4]`になるハズですが、
無くても問題なく処理できるところなので見逃していたようです
修正しておきます
